force-app/main/default/objects/Adress__c/Adress__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adress__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Name &amp; &quot; &quot; &amp;  City__c + &quot;,&quot; &amp;  Text(State__c) &amp; &quot; &quot; &amp;  Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>MN#{0000000000}</displayFormat>
        <label>Mail I.D.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To__c</fullName>
    <label>Deliver To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact for Mail</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>What is the status of the Mail</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Pickup</fullName>
                <default>true</default>
                <label>Waiting for Pickup</label>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Inusrance__c.field-meta.xml
<CustomField>
    <fullName>Inusrance__c</fullName>
    <description>Amount covered with Insurance</description>
    <label>Inusrance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <referenceTo>Adress__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Refund_Status__c.field-meta.xml
<CustomField>
    <fullName>Refund_Status__c</fullName>
    <inlineHelpText>Sets what the refund status when a package is missing</inlineHelpText>
    <label>Refund Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Delivery_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTriggers.cls
@isTest
public class TestTriggers {
    
    @isTest
    public static void testAutoSetRefundStatus(){
        //create this so that we only have to deal with the trigger on mail, not the contact trigger
        Account holder = new Account(Name = 'bob');
        insert holder;
        holder = [SELECT Id FROM Account WHERE Name = 'bob'];
        
        //need to insert and grab so that we generate an Id for contact and address to be used for testm
        Contact testc = new Contact(LastName = 'tester', AccountId = holder.Id);
        Adress__c testa = new Adress__c(Name = '1101 boolean drive', Zip_Code__c = '98597');
        insert testc;
        insert testa;
        testc = [SELECT Id FROM Contact WHERE LastName = 'tester'];
        testa = [SELECT Id FROM Adress__c WHERE Name = '1101 boolean drive'];
        
        //now we can do this
        Mail__c testm = new Mail__c(Height__c = 5, Weight__c = 5, Deliver_To__c = testc.Id, 
                               Mailing_Address__c = testa.Id, Inusrance__c = 200);
        
        
        insert testm;
        Test.startTest();
        Mail__c testm2 = [SELECT Delivery_Status__c FROM Mail__c WHERE Height__c = 5];
        testm2.Delivery_Status__c='Missing';
        update testm2;
        Test.stopTest();
        Mail__c resultm = [SELECT Refund_Status__c FROM Mail__c WHERE Height__c= 5];
        System.assertEquals('Waiting for Approval', resultm.Refund_Status__c);
        
        
    }
    @isTest
    public static void testContactCreateTrigger(){
        Contact testC = new Contact(LastName = 'burger');
        Account testA = new Account(Name = 'burger');
        
        insert testA;
        testA = [SELECT Id FROM Account WHERE Name = 'burger'];
        
        test.startTest();
        insert testC;
        test.stopTest();
        
         Contact resultC = [SELECT AccountId FROM Contact WHERE LastName = 'burger'];
        system.assertEquals(testA.Id, resultC.AccountId);
        
    }
}